export const pagCount = [
    {id: 0},
    {id: 1},
    {id: 2},
    {id: 3},
    {id: 4},
    {id: 5},
    {id: 6},
    {id: 7},
    {id: 8},
    {id: 9},
    {id: 10},
    {id: 11},
    {id: 12},
    {id: 13},
    {id: 14},
    {id: 15},
    {id: 16},
    {id: 17},
    {id: 18},
    {id: 19},
]

interface IStatusCode {
    status: string;
    valid: boolean;
}

export const statusCode: IStatusCode[] = [
    {status: "100", valid: true},
    {status: "101", valid: true},
    {status: "102", valid: true},
    {status: "103", valid: true},
    {status: "104", valid: false},
    {status: "105", valid: false},
    {status: "106", valid: false},
    {status: "107", valid: false},
    {status: "108", valid: false},
    {status: "109", valid: false},
    {status: "110", valid: false},
    {status: "200", valid: true},
    {status: "201", valid: true},
    {status: "202", valid: true},
    {status: "203", valid: true},
    {status: "204", valid: true},
    {status: "205", valid: false},
    {status: "206", valid: true},
    {status: "207", valid: true},
    {status: "208", valid: false},
    {status: "209", valid: false},
    {status: "210", valid: false},
    {status: "300", valid: true},
    {status: "301", valid: true},
    {status: "302", valid: true},
    {status: "303", valid: true},
    {status: "304", valid: true},
    {status: "305", valid: true},
    {status: "306", valid: false},
    {status: "307", valid: true},
    {status: "308", valid: true},
    {status: "309", valid: false},
    {status: "310", valid: false},
    {status: "400", valid: true},
    {status: "401", valid: true},
    {status: "402", valid: true},
    {status: "403", valid: true},
    {status: "404", valid: true},
    {status: "405", valid: true},
    {status: "406", valid: true},
    {status: "407", valid: true},
    {status: "408", valid: true},
    {status: "409", valid: true},
    {status: "410", valid: true},
    {status: "411", valid: true},
    {status: "412", valid: true},
    {status: "413", valid: true},
    {status: "414", valid: true},
    {status: "415", valid: true},
    {status: "416", valid: true},
    {status: "417", valid: true},
    {status: "418", valid: true},
    {status: "419", valid: false},
    {status: "420", valid: true},
    {status: "421", valid: true},
    {status: "422", valid: true},
    {status: "423", valid: true},
    {status: "424", valid: true},
    {status: "425", valid: true},
    {status: "426", valid: true},
    {status: "429", valid: true},
    {status: "431", valid: true},
    {status: "444", valid: true},
    {status: "450", valid: true},
    {status: "451", valid: true},
    {status: "497", valid: true},
    {status: "498", valid: true},
    {status: "499", valid: true},
    {status: "500", valid: true},
    {status: "501", valid: true},
    {status: "502", valid: true},
    {status: "503", valid: true},
    {status: "504", valid: true},
    {status: "506", valid: true},
    {status: "507", valid: true},
    {status: "508", valid: true},
    {status: "509", valid: true},
    {status: "510", valid: true},
    {status: "511", valid: true},
    {status: "521", valid: true},
    {status: "522", valid: true},
    {status: "523", valid: true},
    {status: "525", valid: true},
    {status: "599", valid: true},
    {status: "600", valid: false},
]
